//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripId { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string WeatherType { get; set; }
        public Nullable<int> Visibility { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> LocationId2 { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> AutotypeId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual Autotype Autotype { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Order Order { get; set; }
    }
}
